# Generated by Django 4.2.3 on 2024-10-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shamba", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farminsights", old_name="recommendation", new_name="insights",
        ),
    ]
